### ISSUE TITLE
what is the key 'id' appearing in the scan 

### ISSUE THREAD

**Issue by nilaysaha** [sandeepmistry/node-uri-beacon-scanner#20]
Hi,
   I am getting a packet like this from the scan:

` {
  "txPower": -34,
  "url": "https://<validurl>",
  "id": "9576265a6c5142ee9f1c8dfc53b50358",
  "type": "url",
  "rssi": -68,
  "distance": 0.44668359215096315,
  "lastSeen": 1488489996658,
  "tlm": {
    "version": 0,
    "vbatt": 2934,
    "temp": 5,
    "advCnt": 813815,
    "secCnt": 1745318
  }
}
`

What is the field id appearing in the scan ? I do not have my UID / ibeacon mode switched on and neither do they map to this id....

Any clue ...thanks...

**Comment by sandeepmistry** [comment]
The id is the peripheral id from noble: https://github.com/sandeepmistry/noble#peripheral-discovered

On macOS it's the a per machine unique id generated by CoreBluetooth/blued, on Linux the BT address without colons.
